package org.fax4j.spi.hylafax;

import java.util.Map;
import java.util.Properties;

/**
 * Utility used to populate fax4j HylaFAX configuration from environment variables.
 * <p>
 * The following environment variables are mapped to fax4j configuration
 * properties:
 * <ul>
 *   <li>HYFAX_HOST -> org.fax4j.spi.hylafax.host</li>
 *   <li>HYFAX_PORT -> org.fax4j.spi.hylafax.port</li>
 *   <li>HYFAX_USER -> org.fax4j.spi.hylafax.user</li>
 *   <li>HYFAX_PASS -> org.fax4j.spi.hylafax.password</li>
 *   <li>HYFAX_ADMIN -> org.fax4j.spi.hylafax.admin</li>
 *   <li>HYFAX_MODE -> org.fax4j.spi.hylafax.mode</li>
 *   <li>HYFAX_TYPE -> org.fax4j.spi.hylafax.type</li>
 * </ul>
 *
 * @author Autogenerated
 */
public final class HylaFaxEnvironmentConfiguration {
    /**
     * Private constructor to prevent instantiation.
     */
    private HylaFaxEnvironmentConfiguration() {
        super();
    }

    /**
     * Populates the provided {@link Properties} instance with any matching
     * HylaFAX configuration found in the current environment variables.
     * Existing property values will be overridden if corresponding environment
     * variables are present.
     *
     * @param target The {@link Properties} to update
     */
    public static void load(Properties target) {
        if (target == null) {
            return;
        }
        Map<String, String> env = System.getenv();
        put(env, "HYFAX_HOST", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.HOST_PROPERTY_KEY.toString(), target);
        put(env, "HYFAX_PORT", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.PORT_PROPERTY_KEY.toString(), target);
        put(env, "HYFAX_USER", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.USER_NAME_PROPERTY_KEY.toString(), target);
        put(env, "HYFAX_PASS", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.PASSWORD_PROPERTY_KEY.toString(), target);
        put(env, "HYFAX_ADMIN", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.ENABLE_ADMIN_OPERATIONS_PROPERTY_KEY.toString(), target);
        put(env, "HYFAX_MODE", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.MODE_PROPERTY_KEY.toString(), target);
        put(env, "HYFAX_TYPE", HylaFaxClientSpi.FaxClientSpiConfigurationConstants.TYPE_PROPERTY_KEY.toString(), target);
    }

    /**
     * Helper method to copy a single environment variable value into the
     * provided properties.
     *
     * @param env The environment variable map
     * @param envKey The environment variable name
     * @param propertyKey The fax4j property key
     * @param target The properties instance to update
     */
    private static void put(Map<String, String> env, String envKey, String propertyKey, Properties target) {
        String value = env.get(envKey);
        if (value != null && value.length() > 0) {
            target.setProperty(propertyKey, value);
        }
    }
}

